### ISSUE TITLE
Sending RobotMove command?

### ISSUE THREAD

**Issue by mikewrock** [fsuarez6/bcap#2]
Thanks for your excellent work. I'm having trouble moving the robot (the motors are on and I think everything is fine I'm just sending the wrong string).

My code is:

int32_t lval;
lval = 2;
vntParam.bstrVal = SysAllocString(L"P(264,1.5,275,176,16.5,166,0)");
vntParam.vt = VT_BSTR;
bstrCommand = SysAllocString(L"NEXT");
hr = bCap_RobotMove(fd, hRobot, lval, vntParam, bstrCommand);

I get either a 0x80004005 (Function Failed) or 0x80070057 (Invalid argument) for the strings I send. Any examples of how to move the arm would be great

**Comment by fsuarez6** [comment]
@mikewrock, have you checked if the robot can reach that position? 

> `vntParam.bstrVal = SysAllocString(L"P(264,1.5,275,176,16.5,166,0)");`

**Comment by mikewrock** [comment]
Since I'm getting a function failed and not an invalid argument, I have to assume its on the RC7 side that I'm having an issue. I'm sure P(264,1.5,275,176,16.5,166,0) exists because I read it off the teach pendant, though I've been told to use -1 for fig instead of 0. P1 doesn't work either and I've taught it that point.

I'm wondering if there is an RC7 equivalent of Takearm command I need to issue, since I get invalid argument when I try and use it. I'll remove this issue and post an update as soon as I figure it out.

**Comment by mikewrock** [comment]
Ok I feel dumb, I commented this part out. You need to have RobSlave running, this is for RC7:

bstrCommand = SysAllocString(L"ROBSLAVE");
vntParam.bstrVal = SysAllocString(L"1");
vntParam.vt = VT_BSTR;
//hr = bCap_RobotExecute(fd, hRobot, bstrCommand, vntParam, &vntResult);
hr = bCap_ControllerGetTask(fd, hCtrl, bstrCommand, NULL, &hTask);
SysFreeString(bstrCommand);
VariantClear(&vntParam);
if FAILED(hr) {
ROS_INFO("Could not find task %x", hr);
return (hr);
}else ROS_INFO("Got Handle: %d",hTask);
ros::Duration(1).sleep();
hr = bCap_TaskStart(fd, hTask, 1, NULL);
if FAILED(hr) {
ROS_INFO("Could not start task: %x",hr);
return (hr);
}else ROS_INFO("Started Task");
